<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0" xmlns="http://www.tei-c.org/ns/1.0" xmlns:cc="http://web.resource.org/cc/" xmlns:mods="http://www.loc.gov/mods/v3"
    xmlns:oape="https://openarabicpe.github.io/ns" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:tei="http://www.tei-c.org/ns/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xpath-default-namespace="http://www.tei-c.org/ns/1.0">
    <xsl:import href="convert_tei-to-biblstruct_functions.xsl"/>
    <xsl:template match="/">
        <xsl:choose>
            <xsl:when test="$p_stand-alone = true()">
                <xsl:message>
                    <xsl:text>Output: stand-alone TEI/XML file</xsl:text>
                </xsl:message>
                <xsl:result-document href="{$p_output-folder}file/{$v_id-file}.TEIP5.xml" method="xml">
                    <TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:tei="http://www.tei-c.org/ns/1.0">
                        <teiHeader xml:lang="en">
                            <fileDesc>
                                <titleStmt>
                                    <title>Bibliographic data generated from a tei:fileDesc</title>
                                    <xsl:copy-of select="$p_editor"/>
                                </titleStmt>
                                <publicationStmt>
                                    <p>This file is, yet, unpublished</p>
                                </publicationStmt>
                                <sourceDesc>
                                    <p>This file is a born-digital file and was generated by automatic conversion from the TEI/XML file <ref target="{base-uri()}"><xsl:value-of
                                        select="$v_file-name_input"/></ref>.</p>
                                </sourceDesc>
                            </fileDesc>
                            <revisionDesc>
                                <change when="{$p_today-iso}" who="{$p_id-editor}">Created this file through automated conversion from TEI/XML</change>
                            </revisionDesc>
                        </teiHeader>
                        <standOff>
                            <listBibl>
                                <xsl:apply-templates mode="m_fileDesc-to-biblStruct" select="tei:TEI/tei:teiHeader/tei:fileDesc"/>
                            </listBibl>
                        </standOff>
                    </TEI>
                </xsl:result-document>
            </xsl:when>
            <xsl:when test="$p_stand-alone = false()">
                <xsl:message>
                    <xsl:text>Output: TEI/XML fragments</xsl:text>
                </xsl:message>
                <xsl:result-document href="{$p_output-folder}file/{$v_id-file}_fragment.TEIP5.xml" method="xml">
                    <xsl:apply-templates mode="m_fileDesc-to-biblStruct" select="tei:TEI/tei:teiHeader/tei:fileDesc"/>
                </xsl:result-document>
            </xsl:when>
        </xsl:choose>
    </xsl:template>
</xsl:stylesheet>
