<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0" xmlns="http://www.tei-c.org/ns/1.0"  xmlns:marc="http://www.loc.gov/MARC21/slim"
    xmlns:oape="https://openarabicpe.github.io/ns" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:tei="http://www.tei-c.org/ns/1.0" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xpath-default-namespace="http://www.tei-c.org/ns/1.0">
    <!-- This stylesheet takes RDF records in XML serialisation as input and generates TEI XML as output -->
    <xsl:include href="convert_rdf-to-tei_functions.xsl"/>
    <!-- output: everything is wrapped in a listBibl -->
    <xsl:template match="/">
        <xsl:result-document href="{$v_file-name_input}.TEIP5.xml" method="xml">
            <TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:tei="http://www.tei-c.org/ns/1.0">
                <teiHeader>
                    <fileDesc>
                        <titleStmt>
                            <title>Bibliographic data converted from RDF/XML to TEI</title>
                        </titleStmt>
                        <publicationStmt>
                            <p>This file is, yet, unpublished</p>
                        </publicationStmt>
                        <sourceDesc>
                            <p>This file is a born-digital file and was generated by automatic conversion from the RDF/XML file <ref target="{$v_url-file}"><xsl:value-of select="$v_file-name_input"/></ref>.</p>
                        </sourceDesc>
                    </fileDesc>
                </teiHeader>
                <standOff>
                    <listBibl>
                    <head><xsl:value-of select="count(descendant::rdf:Description)"/> <gi>tei:biblStruct</gi> created by conversion from <gi>rdf:Description</gi></head>
                    <xsl:apply-templates/>
                </listBibl>
                </standOff>
            </TEI>
        </xsl:result-document>
    </xsl:template>
</xsl:stylesheet>
