<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="3.0" xmlns="http://www.tei-c.org/ns/1.0"  xmlns:marc="http://www.loc.gov/MARC21/slim"
    xmlns:oape="https://openarabicpe.github.io/ns" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:tei="http://www.tei-c.org/ns/1.0" xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xpath-default-namespace="http://www.tei-c.org/ns/1.0">
    <!-- This stylesheet takes MARC21 records in XML serialisation as input and generates TEI XML as output -->
    <!-- documentation of the MARC21 field codes can be found here: https://marc21.ca/M21/MARC-Field-Codes.html -->
    <xsl:include href="convert_marc-xml-to-tei_functions.xsl"/>
    <!-- output: everything is wrapped in a listBibl -->
    <xsl:template match="/">
        <xsl:result-document href="{$v_base-directory}metadata/{$v_file-name_input}.TEIP5.xml" method="xml">
            <TEI>
                <teiHeader>
                    <fileDesc>
                        <titleStmt>
                            <title>Bibliographic data converted from MARX XML to TEI</title>
                        </titleStmt>
                        <publicationStmt>
                            <p>This file is, yet, unpublished</p>
                        </publicationStmt>
                        <sourceDesc>
                            <p>This file is a born-digital file and was generated by automatic conversion from the MARCXML file <ref target="{base-uri()}"><xsl:value-of select="$v_file-name_input"/></ref>.</p>
                        </sourceDesc>
                    </fileDesc>
                </teiHeader>
                <standOff>
                    <listBibl>
                        <xsl:apply-templates select="descendant::marc:record"/>
                    </listBibl>
                </standOff>
            </TEI>
        </xsl:result-document>
    </xsl:template>
</xsl:stylesheet>
